---
vm_list:
  - name: vm-ai-inference
    vmid: 9001
    cores: 12
    memory: 49152
    disk_size: 200
    ip: 10.10.10.10
    gpu_passthrough: true
    pci_id: "01:00"
  - name: vm-ai-apps
    vmid: 9002
    cores: 8
    memory: 49152
    disk_size: 300
    ip: 10.10.10.11
    gpu_passthrough: false
    pci_id: ""
